name: FastAPI book application - bundled with N8N
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   SQL_DATABASE_URL: postgresql://neondb_owner:npg_Gfza4P1MQwET@ep-jolly-math-ad4f70k0-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    #   # Safe values just for testing JWT functionality
    #   JWT_SECRET_KEY: testsecretkey
    #   JWT_HASH_ALGORITHM: HS256
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.14
      uses: actions/setup-python@v1
      with:
        python-version: 3.14
    - name: Install dependencies
      run: |
        make install
    - name: Create .env file
      run: |
        touch .env
        echo "SQL_DATABASE_URL=${{ secrets.SQL_DATABASE_URL }}" >> .env
        echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
        echo "JWT_HASH_ALGORITHM=${{ secrets.JWT_HASH_ALGORITHM }}" >> .env
    - name: Fromat code
      run: |
        make format
    - name: Lint code
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: build container
      run: |
        make build
