name: FastAPI book application - bundled with N8N
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.14
      uses: actions/setup-python@v1
      with:
        python-version: 3.14
    - name: Install dependencies
      run: |
        make install
    - name: Create .env file
      run: |
        touch .env
        echo "SQL_DATABASE_URL=${{ secrets.SQL_DATABASE_URL }}" >> .env
        echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
        echo "JWT_HASH_ALGORITHM=${{ secrets.JWT_HASH_ALGORITHM }}" >> .env
    - name: Fromat code
      run: |
        make format
    - name: Lint code
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: build container
      run: |
        make build
